---
# tasks file for argocd

- name: argocd app deployment
  community.kubernetes.k8s:
    state: "{{ item.argocdState }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata: 
        name: "{{ item.appName }}"
        namespace: "{{ item.argocdNamespace }}"
      spec: 
        destination:
          namespace: "{{ item.appNamespace }}"
          server: "{{ item.k8sServer }}" 
        project: "{{ item.argocdProject }}"
        source:
          path: "{{ item.repoPath }}"
          repoURL: "{{ item.repoURL }}"
          targetRevision: "{{ item.repoTargetRevision }}"
#          helm:
#            releaseName: "{{ item.helmReleaseName }}"
        syncPolicy:
          syncOptions: 
          - 'CreateNamespace=true'
          automated:
            selfHeal: "{{ item.selfHeal }}"
  loop: "{{ argovars }}" 
